version: "3"
services:
  db1:
    image: mysql
    volumes: 
      - db:/var/lib/mysql
  db2:
    image: mongo
    volumes: 
      - db:/var/lib/mongo
  assignapp:
    depends_on:
      - db1
    image: finalapp
    ports:
      - 5000:3000
    volumes: 
      - db:/var/lib/finalapp
volumes:
  db:
